version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bookingx
      POSTGRES_USER: bookingx
      POSTGRES_PASSWORD: bookingx
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookingx -d bookingx"]
      interval: 5s
      timeout: 5s
      retries: 20
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookingx
      SPRING_DATASOURCE_USERNAME: bookingx
      SPRING_DATASOURCE_PASSWORD: bookingx
      APP_SECURITY_JWT_SECRET: change-me-very-long-secret-key-please
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  db_data:

